# Generated by Django 6.0.2 on 2026-02-23 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['-rating', '-total_jobs']},
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='call_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='member_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
