# Generated by Django 6.0.2 on 2026-02-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceprovider_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='aadhar_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
